telegram_token = "telegram bot token"

command_start_message = "Здравствуйте, пожалуйста выберите район для подачи жалобы."
complaint_readme = """
Для подачи жалобы, пожалуйста, напишите её в чат и нажмите кнопку 'Отправить жалобу'
Вы так же можете писать жалобу в несколько сообщений и при необходимости просмотреть её текст по кнопке 'Просмотреть жалобу'
В случае если вы передумали или хотите изменить содержание жалобы, то можете удалить её по кнопке 'Удалить жалобу'
Для смены района нажмите кнопку 'Сменить район'
"""
district_set = "Район '{}' установлен!."
district_not_found = "Район '{}' не найден!."
admin_hello_message = "Здравствуйте, для просмотра жалоб пожалуйста нажмите кнопку"
complaint_sent = "Жалоба отправлена!"
complaint_removed = "Жалоба удалена!"
complaint_view = "Ваша жалоба:"
no_complaint = "Вы еще не написали жалобу!"
complaints = "Жалобы:"
no_permission = "У вас нет прав на использование данной команды!"

districts = [
    "Адмиралтейский",
    "Василеостровский",
    "Выборгский",
    "Калининский",
    "Кировский",
    "Колпинский",
    "Красногвардейский",
    "Красносельский",
    "Кронштадтский",
    "Курортный",
    "Московский",
    "Невский",
    "Петроградский",
    "Петродворцовый",
    "Приморский",
    "Пушкинский",
    "Фрунзенский",
    "Центральный",
]

[mongodb]
host = "localhost"
port = "27017"
login = "admin"
password = "admin"
dbName = "telegram-complaint-bot"
authDb = "admin"